/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment0056;

/**
 *
 * @author Pasindu Malinda
 */
public class gpaCalculator extends javax.swing.JFrame {

    /**
     * Creates new form gpaCalculator
     */
    public gpaCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        oneTF = new javax.swing.JTextField();
        twoTF = new javax.swing.JTextField();
        threeTF = new javax.swing.JTextField();
        averageTF = new javax.swing.JTextField();
        fourTF = new javax.swing.JTextField();
        dLetterTF = new javax.swing.JTextField();
        eLetterTF = new javax.swing.JTextField();
        aLetterTF = new javax.swing.JTextField();
        bLetterTF = new javax.swing.JTextField();
        cLetterTF = new javax.swing.JTextField();
        fiveTF = new javax.swing.JTextField();
        gpaTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CalculateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Grade & GPA Calculator");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("HNDIT 2012 :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("HNDIT 2022 :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("HNDIT 2032 :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("HNDIT 2042 :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Average :");

        oneTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        twoTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        threeTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        averageTF.setEditable(false);
        averageTF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        averageTF.setForeground(new java.awt.Color(51, 51, 255));

        fourTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        dLetterTF.setEditable(false);
        dLetterTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        dLetterTF.setForeground(new java.awt.Color(255, 51, 51));

        eLetterTF.setEditable(false);
        eLetterTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        eLetterTF.setForeground(new java.awt.Color(255, 51, 51));

        aLetterTF.setEditable(false);
        aLetterTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        aLetterTF.setForeground(new java.awt.Color(255, 51, 51));

        bLetterTF.setEditable(false);
        bLetterTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bLetterTF.setForeground(new java.awt.Color(255, 51, 51));

        cLetterTF.setEditable(false);
        cLetterTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cLetterTF.setForeground(new java.awt.Color(255, 51, 51));

        fiveTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        gpaTF.setEditable(false);
        gpaTF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gpaTF.setForeground(new java.awt.Color(255, 0, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("HNDIT 2052 :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("GPA :");

        CalculateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(51, 51, 255));
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(0, 102, 51));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 51, 51));
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Grade");

        jLabel10.setText("Marks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalculateButton)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(oneTF)
                                .addComponent(twoTF)
                                .addComponent(threeTF)
                                .addComponent(fourTF)
                                .addComponent(fiveTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dLetterTF)
                                    .addComponent(bLetterTF)
                                    .addComponent(cLetterTF)
                                    .addComponent(eLetterTF)
                                    .addComponent(aLetterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(averageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aLetterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(bLetterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cLetterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dLetterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eLetterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiveTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(averageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateButton)
                    .addComponent(ClearButton)
                    .addComponent(ExitButton))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        
    // get marks
        
        String oneScore, twoScore, threeScore, fourScore, fiveScore;
        double average;
        double gpa = 0;
        
        oneScore = oneTF.getText();
        twoScore = twoTF.getText();
        threeScore = threeTF.getText();
        fourScore = fourTF.getText();
        fiveScore = fiveTF.getText();
        
        double one = Double.parseDouble(oneScore);
        double two = Double.parseDouble(twoScore);
        double three = Double.parseDouble(threeScore);
        double four = Double.parseDouble(fourScore);
        double five = Double.parseDouble(fiveScore);
        
    // calculate marks
        
        average = ((one + two + three + four + five) / 5);
        averageTF.setText(Double.toString(average));
        
    // HNDIT 2012 Subject Grade & GPA value
    
    if (one >= 90){
            aLetterTF.setText("A");
            gpa = gpa + 4.0;
        } else if (one >= 80 && one < 90){
            aLetterTF.setText("B");
            gpa = gpa + 3.0;
        } else if (one >= 70 && one < 80){
            aLetterTF.setText("C");
            gpa = gpa + 2.0;
        } else if (one >= 55 && one < 70){
            aLetterTF.setText("D");
            gpa = gpa + 1.0;
        } else{
            aLetterTF.setText("F");
            gpa = gpa + 0.0;
        }
    
    // HNDIT 2022 Subject Grade & GPA value
    
    if (two >= 90){
            bLetterTF.setText("A");
            gpa = gpa + 4.0;
        } else if (two >= 80 && two < 90){
            bLetterTF.setText("B");
            gpa = gpa + 3.0;
        } else if (two >= 70 && two < 80){
            bLetterTF.setText("C");
            gpa = gpa + 2.0;
        } else if (two >= 55 && two < 70){
            bLetterTF.setText("D");
            gpa = gpa + 1.0;
        } else{
            bLetterTF.setText("F");
            gpa = gpa + 0.0;
        }
    
    // HNDIT 2032 Subject Grade & GPA value
    
    if (three >= 90){
            cLetterTF.setText("A");
            gpa = gpa + 4.0;
        } else if (three >= 80 && three < 90){
            cLetterTF.setText("B");
            gpa = gpa + 3.0;
        } else if (three >= 70 && three < 80){
            cLetterTF.setText("C");
            gpa = gpa + 2.0;
        } else if (three >= 55 && three < 70){
            cLetterTF.setText("D");
            gpa = gpa + 1.0;
        } else{
            cLetterTF.setText("F");
            gpa = gpa + 0.0;
        }
    
    // HNDIT 2042 Subject Grade & GPA value
    
    if (four >= 90){
            dLetterTF.setText("A");
            gpa = gpa + 4.0;
        } else if (four >= 80 && four < 90){
            dLetterTF.setText("B");
            gpa = gpa + 3.0;
        } else if (four >= 70 && four < 80){
            dLetterTF.setText("C");
            gpa = gpa + 2.0;
        } else if (four >= 55 && four < 70){
            dLetterTF.setText("D");
            gpa = gpa + 1.0;
        } else{
            dLetterTF.setText("F");
            gpa = gpa + 0.0;
        }
    
    // HNDIT 2052 Subject Grade & GPA value
    
    if (five >= 90){
            eLetterTF.setText("A");
            gpa = gpa + 4.0;
        } else if (five >= 80 && five < 90){
            eLetterTF.setText("B");
            gpa = gpa + 3.0;
        } else if (five >= 70 && five < 80){
            eLetterTF.setText("C");
            gpa = gpa + 2.0;
        } else if (five >= 55 && five < 70){
            eLetterTF.setText("D");
            gpa = gpa + 1.0;
        } else{
            eLetterTF.setText("F");
            gpa = gpa + 0.0;
        }
    
        gpa = gpa / 5;
        gpaTF.setText(Double.toString(gpa));
        
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        
    // Apllication Exit
    
        this.setVisible(false);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        
    // For Application Form Clear
    
        oneTF.setText(null);
        twoTF.setText(null);
        threeTF.setText(null);
        fourTF.setText(null);
        fiveTF.setText(null);
        aLetterTF.setText(null);
        bLetterTF.setText(null);
        cLetterTF.setText(null);
        dLetterTF.setText(null);
        eLetterTF.setText(null);
        averageTF.setText(null);
        gpaTF.setText(null);
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gpaCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField aLetterTF;
    private javax.swing.JTextField averageTF;
    private javax.swing.JTextField bLetterTF;
    private javax.swing.JTextField cLetterTF;
    private javax.swing.JTextField dLetterTF;
    private javax.swing.JTextField eLetterTF;
    private javax.swing.JTextField fiveTF;
    private javax.swing.JTextField fourTF;
    private javax.swing.JTextField gpaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField oneTF;
    private javax.swing.JTextField threeTF;
    private javax.swing.JTextField twoTF;
    // End of variables declaration//GEN-END:variables
}
